name: Build and Deploy DOJ Website

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Tailwind CSS
      run: npm run build
      
    - name: Check if style.css was generated
      run: |
        if [ ! -f style.css ]; then
          echo "Error: style.css was not generated"
          exit 1
        else
          echo "✅ style.css generated successfully"
          ls -la style.css
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-website
        path: |
          *.html
          *.css
          *.js
          assets/
          memorandums/
        retention-days: 30
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for production
      run: npm run build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: |
          node_modules/
          .github/
          build.sh
          build.bat
          input.css
          package*.json
          tailwind.config.js
          postcss.config.js
